build:
  environment:
    php:
      version: 7.2.17 # Common versions: 5.4, 5.5, 5.6, 7.0 or hhvm
  tests:
    override:
      -
        command: 'vendor/bin/phpunit --exclude-group=IntegrationTest --configuration phpunit.dist.xml --coverage-clover=clover.xml '
        coverage:
          file: 'clover.xml'
          format: 'php-clover'
