language: php
sudo: false

php:
  - 7.1
  - 7.2  
  - nightly

matrix:
  include:
    - php: hhvm
      dist: trusty
  fast_finish: true
  allow_failures:
  - php: hhvm
  - php: nightly

install:
  - composer self-update
  - composer install --no-interaction

before_script:
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --exclude-group=IntegrationTest --configuration phpunit.dist.xml --coverage-clover build/logs/clover.xml ./tests
  - ./vendor/bin/phpcs --standard=PSR2 src

after_script:
  - php vendor/bin/coveralls -v
